---

- set_fact: "ls_major_version={{ ls_logstash_version.split('.')[0] }}.x"
  when:
      - ls_major_version is undefined
  tags:
      - always

- name: include logstash-install.yml
  ansible.builtin.include_tasks: logstash-install.yml
  tags:
      - install
  # when: es_is_install

- name: include logstash-certs.yml
  ansible.builtin.include_tasks: logstash-certs.yml
  tags:
      - install
      - pipelines
  # when: es_is_install

- name: include logstash-config.yml
  ansible.builtin.include_tasks: logstash-config.yml
  tags:
      - install
      - pipelines
  # when: es_is_install

- name: include logstash-pipelines.yml
  ansible.builtin.include_tasks: logstash-pipelines.yml
  tags:
      - install
      - pipelines
  # when: es_is_install

- name: include logstash-startup.yml
  ansible.builtin.include_tasks: logstash-startup.yml
  tags:
      - install
  # when: es_is_install
